spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://commerce-backend-mysql-1:3306/commerce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kafka:
  bootstrap-servers: commerce-backend-kafka-1:9092

server:
  port: 8082

commerce:
  service:
    url: http://commerce-backend-1:8080

resilience4j:
  retry:
    instances:
      commerceService:
        max-attempts: 3
        wait-duration: 1s

  circuitbreaker:
    instances:
      commerceService:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

paypal:
  base-url: https://api-m.sandbox.paypal.com
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
